steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/blast-radius:$SHORT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/blast-radius:$SHORT_SHA
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - blast-radius
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/blast-radius:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --set-env-vars=DEMO_MODE=true,USE_GEMINI_SUMMARY=true,ENVIRONMENT=prod

substitutions:
  _REGION: us-central1
  _REPOSITORY: hackathon

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/blast-radius:$SHORT_SHA
